[package]
name = "rtimer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
indicatif = "0.18.2"
notify-rust = { version = "4.11.7", features = ["image"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
